### ISSUE TITLE
Connect button interactions with the back-end

### ISSUE THREAD

**Issue by cspears8** [COSC481W-2024Fall/Project-Ghost#31]
### User Story
I would like to start the game when I am ready to play rather than the game immediately starting and I die.

- **Persona**: Someone who does not want to immediately start the game when loading the page, they may want to look at the leader board first. They may also have dexterity issues and may not be able to start playing immediately
- **Feature**: A title screen that shows the title of our game as well as relevant information such as leader boards and controls
- **Business value**: This allows users to not be frustrated by having to quickly start playing the game every time they refresh the page, they can start when they want

As a person who hates restarting entire applications, I would like to see a title screen that shows relevant information of the game such a leader boards while not being frustrated by having to quickly start the game.

- [x] #29
- [x] #30
- [x] #31

**Acceptance Tests**
1. The web page should start from this screen
2. There should be a play button which starts the game
3. There should be a leaderboard button
4. There should be a tutorial button which explains controls

**Acceptance Criteria**

1. The UI can be simple, should be mostly utility driven
2. The leaderboard does not have to have anything but a way to go back to the main menu
3. The tutorial can just be text for now
### Description
There should be a JavaScript file for handling button clicks, this should be in a file called TitleScreenUI or something similar. When the user clicks each button they each do their respective task. 

- **Leaderboard**: The page should just be blank for now with a back button since we will work on that task during Sprint 2. 
- **Controls**: The page ideally would have key icons showing controls and would dynamically change when a mobile device is detected (this can be done in a variety of ways including checking screen width, as well as checking userAgent). If there is no time we can use text for this sprint. Of course this page also has a back button.
- **Play**: This button should just load the game!
Below is a code example for a JavaScript function that handles button clicks between the front and back end.

### Code Example:
```javascript
// This is a JavaScript code block
function authenticateUser(username, password) {
    // Call the backend API to authenticate the user
    return fetch('/api/auth', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password })
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            console.log('User authenticated!');
        } else {
            console.log('Authentication failed.');
        }
    });
}

**Comment by joyouswonders** [comment]
merged code for this in GitHub
