### ISSUE TITLE
Leaderboard Structure

### ISSUE THREAD

**Issue by cspears8** [COSC481W-2024Fall/Project-Ghost#42]
### User Story
I would like to be able to see where I am on the leader board, and check high scores for the day, week, and all time.

- **Persona**: Someone who wants to show where they or their friends are on the leader board
- **Feature**: A table for seeing the top 10 high scores for the day, week, and all time
- **Business Value**: It is hard to see how well I did or to keep track of my placement when there is no UI for it!
<br>

- [x] #46 
- [x] #47 

**Acceptance Tests**
1. There is an HTML element (maybe a table) that is shown below the game view when a user either gets put on the leader board, or they click the leader board option in the menu
2. The table shows the top ten scores in the respective categories, if there are less than 10 scores they should be blank
3. There are 3 different tabs in the table: daily, weekly, and all time
4. Ties should be broken by the time the user got the score

**Acceptance Criteria**
1. The leader board can just be an HTML table for now, we can implement the art later on

**Comment by sjiang1** [comment]
I moved this PBI to "Sprint Backlog". In the future, please don't forget to move the PBIs to Sprint Backlog.

**Comment by sjiang1** [comment]
Based on the sprint planning meeting, the end date is Oct. 31? I updated the end date here. Please let me know if it's incorrect.

![Image](https://github.com/user-attachments/assets/9e54c73b-d299-4fdc-a77f-b3b8451ed938)
