### ISSUE TITLE
UI Implementation

### ISSUE THREAD

**Issue by joyouswonders** [COSC481W-2024Fall/Project-Ghost#43]
### User Story

I would like to be able to see graphics that do not look so experimental.
- **Persona**: Someone who wants to see better graphics in the game going forward
- **Feature** Implement UI assets that have been designed.
- **Business Value**: The game seems boring without UI.
<be>

- [x] Upload assets
- [x] CSS monkeying
- [x] etc..
- [x] manual checking/testing

**Acceptance Tests**
    Images are loaded into the game during gameplay.
   
**Acceptance Criteria**
   Images do not have to look perfect, but they are better than a solid white background with black writing.
   There will be no changes to player or enemy graphics.

**Comment by sjiang1** [comment]
I am not sure what's the timeline for this PBI. I added start and end dates here. You can adjust the dates.
![Image](https://github.com/user-attachments/assets/2f1fa65e-ca20-4c5d-b87b-4aa3fb39d037)

**Comment by joyouswonders** [comment]
This is the list of things to do in Sprint 2, so I used the Sprint 2 ending date for it.
