### ISSUE TITLE
File separation (Javascript)

### ISSUE THREAD

**Issue by natecampbell007** [COSC481W-2024Fall/Project-Ghost#44]
As someone who doesn't like cluttered code, I would like to see the main file separated into smaller JavaScript files for less clutter and more manageable files.

- **Persona**: Someone who is interested in looking at the insides of a program.
- **Feature**: A user-friendly approach to anyone that wants to view the code.
- **Business Value**: Easier for investors or fellow coding-savvy users to understand the breakdown of the code. 

As someone who is interested in looking at the insides of a program, I would love to see the main JavaScript files separated into smaller files that can make it user-friendly for investors or tech-savvy users to understand the code of the program. 

- [ ] Separate the files and have the layout planned.
- [ ] Optimize the files to where only one JavaScript file is in the html file and implement import and export for variables and functions.
- [ ] Implement asset files to integrate with the game for characters to have design instead of basic obstacles.
- [ ] #52

**Acceptance Tests**
1. The program should run and have all user-playing options available on launch.
2. Button input should be registered as well as high-score submissions.

**Acceptance Criteria**
1. Program should be fully functional once implementations are set.
2. Code should be cleaned up and manageable with multiple JavaScript files.

### Description
Separate the main JavaScript file and split it into multiple files that allow the program to function normally while having an organized layout.

**Comment by sjiang1** [comment]
I moved this PBI from No Status to "Sprint Backlog". In the future, please don't forget to move the PBIs to Sprint Backlog.

**Comment by sjiang1** [comment]
This PBI is a maintenance task. So you don't need a user story. Please revise this PBI.

**Comment by sjiang1** [comment]
I put start and end dates on this PBI card. Please double check the dates.
![Image](https://github.com/user-attachments/assets/9281c72e-7dd0-489b-a516-e58830c1a0c4)
