### ISSUE TITLE
Advanced Level Generation

### ISSUE THREAD

**Issue by heliguy4599** [COSC481W-2024Fall/Project-Ghost#51]
# User Story
Currently the level generation is boring and repetitive. I would like to see more interesting obstacle layouts, and the level to be more challenging as my play time increases.

- **Persona**: Someone who would be bored with repetitive game-play, and wishes for a challenging game
- **Feature**: Advanced level-generation that gets harder as the game continues
- **Business Value**: The game will be more attractive to more people, and will keep it from becoming boring to current players

- [x] Increase amount of objects on screen as score increases
- [x] Decide upon math equation to scale difficulty with score
- [x] Implement checks to ensure impossible object formations can't be generated
- [x] Store data in obstacles about collision types

# Acceptance Tests

1. The same exact level should be generated from the same seed to ensure replayability
2. The level should get noticeably harder as the score increases
3. The level should not become impossibly hard within 2 minutes of gameplay

# Acceptance Criteria

1. The difficulty of the level scales fairly with score over 2 minutes
2. The layout of obstacles shouldn't feel boring

**Comment by sjiang1** [comment]
I added this PBI to the GitHub board. Please make sure to add issues to the project board in the future. :-)

**Comment by sjiang1** [comment]
No assignees for this issue.
I am not sure when this PBI will be finished. I added start and end date here, you can adjust the dates.

![Image](https://github.com/user-attachments/assets/4b9efd29-a381-4f60-bf67-970d174f917d)
